CISSSO Integration (Quality of Life Updates to analysis.py)
jfcabana/omg_dosimetry pull request #34
Opened 2023-11-30 15:29 UTC by petruong

Hello there. Here at CISSSO, we've been using/updating from a version of OMG Film Dosimetry python modules prior to its introduction here onto Github. Going to try to keep the summarized changes brief and focus on the major updates/feature revisions.
Additional information (i.e., thought process/explanation for re-work) can be found in commit descriptions.  

General formatting:
- New line statements to improve print readability
- Tried to maintain function/script description/commentary

analysis.py:
- norm_film_dose integration: added the possibility to use a separate scan for the normalization film (i.e., 300 MU). If exists, it will be used to acquire the reference normalization factor. Having a separate scan can be useful if multiple patient QA has been scanned during the same day, to which the separate normalization scan (scan image files) can be re-used.  Another use would be if there exists lateral/longitudinal scanner response issues where scanning in the center of the scanner (for both the QA and normalization film) would decrease this response effect.
- Fixed up some issues with closing the self.fig (commonly found in functions depending on an event/action) prior to the call for plt.wait, where there will be a missing fig/plt instance pointing to it. Spyder is able to work around this, but other IDE unfortunately will crash as a consequence. 
 - Updated the plt.wait statement to be 1 second as opposed to 5 second. Quicken the workflow a bit (definitely more convenient when testing code, but also nice to just be generally faster). 
- Vertical line present in profiles created (during show_results) to give a better idea of its relation to the crosshair (profile lines) drawn on the results (film, reference, gamma, RSE plots)
- Inclusion of filename of the film and reference dose in the results figure title per axis
 - Inclusion of the particular gamma analysis criteria in the title of the results figure
- select_markers function has been reworked to simplify view and general usage
 - Limit number of marker selection to 4
 - Fixed a bug where ax.clear() would occur when pressing "hotkeys" for zoom/full-screen (and obviously other tools). This would conflict with the self.film_dose.array manipulations (rotate, flip, etc.). 
  - Removed markers when these manipulations occur as the array/figure has changed
 - Added an option where if no markers are selected, the top, right, bottom, left (center) sides have been selected
  - Not perfect, but at least it serves as an option where markers were forgotten/omitted during the irradiation step. Further registration position tuning can be done to further align.
- set_profiles function has been reworked that now includes clicking in the profile to change the view in the other profile (vertical line: ultimately moving the crosshair as well)
 - Required introducing a self.prof_x, y variable to store the profile position
 - Cleaned up set_profiles function in general to simply be based on the cursor type and a click

calibration.py
- Added default parameter for variable savefile in show_results function call. When working with the calibration python module (command line prompts), not relevant to have to the savefile save/exist when wanting to view the results.

tiff2dose.py
- Updated the clim range for consistency, disturbance, residuals as the previous values did not show much relevant information that could be extracted

OMG_CISSSO_Test.py:
- Included example QA patient tiff2analysis test file to demonstrate how the OMG film dosimetry python module is implemented/utilized at CISSSO.
- Useful implementation would be the selection of the scan, reference dose file path
- Future implementation would be to fully integrate the input for info variable, LUT selection, other tiff2dose parameters perhaps.

Happy reviewing.
Cheers,
Peter

2023-12-04 17:52 UTC, LuisOlivaresJ commented
Hi there,

I only have some experience using calibration.py. The changes there are ok to me.

2023-12-06 20:09 UTC, petruong commented
Note: pull request has been updated from my recent commit (2023-12-06)... 
Review edited description (bottom) for additional details.

2023-12-11 17:14 UTC, jfcabana requested changes
Seems all good, except for the changing of x_axis in profiles plots to pixels. See comments below.

2023-12-11 17:14 UTC, jfcabana commented on src/omg_dosimetry/analysis.py
> -            x_axis = (np.array(range(0, len(film_prof))) / self.film_dose.dpmm).tolist()
I think it would be better to leave the profiles x_axis to mm. It used to be in pixels, but I changed it to mm because we want to be able use this axis to estimate a physical offset between the film dose profile and reference dose profile. 

If it is bothering to have different axis for the dose plots and profile plots, it would make more sense to change the other  plots to mm.

After testing, I realize that changing to pixels also screws up my profile offsets analysis, as the move_profile_ontype function would now apply shifts by 0.1 pixel increment instead of 0.1 mm as intended.

2023-12-11 17:14 UTC, jfcabana commented on src/omg_dosimetry/analysis.py
> -        ax.set_xlabel('Position (mm)')
:(

2023-12-15 18:18 UTC, petruong commented on src/omg_dosimetry/analysis.py
> -            x_axis = (np.array(range(0, len(film_prof))) / self.film_dose.dpmm).tolist()
Updated from recent commit (2023-12-15).

2023-12-15 20:09 UTC, jfcabana approved these changes
All good!

2023-12-15 21:15 UTC, merged